name = pickets
title = Pickets
description = Adds, decorative (creative mode only) picket & fancy picket fences & gates (gates are customizable using 2 textures), and flower boxes to hang on pickets and under windows.
depends = default, doors
optional_depends = bucket
game_support = mintest_game
